### ISSUE TITLE
Comment, Member CRUD

### ISSUE THREAD

**Issue by yu-heejin** [Techeer3-Spring-Study/TAB-Backend#14]

**Comment by Zzyoon** [comment]
issue

**Comment by Zzyoon** [comment]
혹시 좀 있다 미팅때 안 보일까봐 미리 캡쳐해서 올려둡니당..
<img width="514" alt="스크린샷 2023-01-02 21 22 52" src="https://user-images.githubusercontent.com/98005864/210230707-59e36325-7c1d-45df-9e81-3426660f7a81.png">
*댓글 작성 : api url에서 postid를 받아와서 json body에 따로 명시하지 않아도 넘어가게 @pathvariable을 적용해보려했는데 실패해서 body에도 적어야 전송이 되는 상태입니다..ㅜ
<img width="705" alt="스크린샷 2023-01-02 21 24 23" src="https://user-images.githubusercontent.com/98005864/210230884-f87f8b0b-f9ac-4b32-a31c-fa0714304f25.png">
*댓글 목록 불러오기는 잘 됩니다
<img width="732" alt="스크린샷 2023-01-02 21 24 46" src="https://user-images.githubusercontent.com/98005864/210230929-1bd363ec-6a5c-4a8d-a95b-f62c9ae2fcba.png">
*댓글 수정에서 500에러가 나는데... 이건 어디서 잘 못 됐는지 모르겠어요ㅜㅜ 해결중입니다..
<img width="710" alt="스크린샷 2023-01-02 21 25 31" src="https://user-images.githubusercontent.com/98005864/210231006-6edf7b7b-da86-4852-80a4-5feec10dbf0e.png">
*댓글 삭제도 잘 됩니다
